.TH "pam_auks.so.8" "Jun 2017" "David Johnson" "pam_auks.so"

.SH "NAME"
pam_auks.so \- AUKS PAM session plugin

.SH "SYNOPSIS"
.HP \w'\fBpam_auks\&.so\fR\ 'u
\fBpam_auks\&.so\fR [quiet] [syslog]

\fB
.SH "DESCRIPTION"

.LP
\fBpam_auks.so\fR is a PAM plugin that updates krb5 credentials 
to AUKS whenever the user logs in or unlocks their screen.

.SH "EXAMPLES"
.PP
If you need to update auks's credentials each time a user logs-in:  
.PP
.RS 4
session optional pam_auks\&.so [arguments]
.PP

.SH "OPTIONS"
.PP
\fBquiet\fR
.RS 4
Whether to logs informative messages or not. Error messages are not affected.
.RE
.PP
\fBsyslog\fR
.RS 4
Whether to use pam messages or syslog messages for the logs. Defaults to PAM logs (pam_verror/pam_vinfo).
.RE

.SH "COPYING"
.LP
Copyright  (2017)
.br

.SH "SEE ALSO"
.BR auks (1),
